os:
  - linux
  - osx

language: ruby

before_install:
  - rvm get stable
  - rvm reload
  - if [ $TRAVIS_OS_NAME = linux ]; then
      travis_retry sudo apt-get install indent;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
      travis_retry brew install gnu-indent --with-default-names;
    fi

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - gem update --system || test true
  - gem install bundler --no-document || test true
  - bundle install --without development --jobs 3 --retry 3
  - bundle exec rake complete
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

env:
  - CC=gcc
  - CC=clang

matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
